KAFKA_BROKERS: localhost:9092
PRIVACY_PROCESSOR_CONSUMER_GROUP: privacy-processor
DEVICE_STATUS_TOPIC: topic.device.status
PRIVACY_FENCE_TOPIC: table.device.privacyfence
DEVICE_STATUS_PRIVATE_TOPIC: topic.device.status.private
